## 什么是PyTorch

PyTorch是一个基于python的科学计算包，主要针对两类人群：
* 作为NumPy的替代品，可以利用GPU的性能进行计算
* 作为一个高灵活性、速度快的深度学习平台

## 张量

`Tensor` 类似于 `Numpy` 的 `ndarray` ，但还可以在GPU上使用来加速计算。

`Tensor` 是 `PyTorch` 中重要的数据结构，可认为是一个高维数组。它可以是 `一个数（标量）` 、 `一维数组（向量）` 、 `二维数组（矩阵）` 以及更 `高维的数组` 。Tensor和Numpy的ndarrays类似，但Tensor可以使用GPU进行加速。Tensor的使用和Numpy及Matlab的接口十分相似。

**导入 `PyTorch` 包**

In [1]:
import torch

**创建一个没有初始化的 `5 * 3` 矩阵**

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


**创建一个随机初始化的 `5 * 3` 矩阵**

In [3]:
 x = torch.rand(5, 3)
print(x)

tensor([[0.3262, 0.8605, 0.3583],
        [0.6820, 0.7553, 0.2888],
        [0.2928, 0.7479, 0.0470],
        [0.5299, 0.1583, 0.8232],
        [0.1096, 0.2576, 0.6104]])


**构造一个全部为 `0` 且数据类型为 `long` 的 `5 * 3` 矩阵**

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


**直接从数据构造张量**

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


**根据已有的 `tensor` 建立新的 `tensor`**

除非用户提供新的值，否则这些方法将重用输入张量的属性，例如 `dtype` 等。

In [6]:
# new_* methods take in sizes
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
# 重载dtype，结果有相同的size
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.3302,  0.2553, -0.5273],
        [ 0.0882,  0.2170, -0.4866],
        [-0.2964, -0.1960, -1.3247],
        [-0.3479,  1.3610, -0.4364],
        [ 0.5204,  1.7581,  0.2340]])


In [8]:
print(x.size())

torch.Size([5, 3])


> 注意：<br>
`torch.Size` 本质上还是 `tuple`，所以支持tuple的一切操作。

## 运算 

**加法：形式1**

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.8451,  0.6908, -0.3946],
        [ 0.4987,  0.2943, -0.1693],
        [-0.1301,  0.5376, -0.6440],
        [ 0.2824,  1.9215, -0.0975],
        [ 0.9350,  1.8784,  0.8255]])


**加法：形式2**

In [10]:
print(torch.add(x, y))

tensor([[ 0.8451,  0.6908, -0.3946],
        [ 0.4987,  0.2943, -0.1693],
        [-0.1301,  0.5376, -0.6440],
        [ 0.2824,  1.9215, -0.0975],
        [ 0.9350,  1.8784,  0.8255]])


**加法：给定一个输出张量作为参数**

In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.8451,  0.6908, -0.3946],
        [ 0.4987,  0.2943, -0.1693],
        [-0.1301,  0.5376, -0.6440],
        [ 0.2824,  1.9215, -0.0975],
        [ 0.9350,  1.8784,  0.8255]])


**加法：原位/原地操作 `in-place`**

In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.8451,  0.6908, -0.3946],
        [ 0.4987,  0.2943, -0.1693],
        [-0.1301,  0.5376, -0.6440],
        [ 0.2824,  1.9215, -0.0975],
        [ 0.9350,  1.8784,  0.8255]])


> 注意：<br>
任何一个 `in-place` 改变张量的操作后面都固定了一个 `_` 。例如 `x.copy_(y)` 、 `x.t_()` 将更改 `x`。<br>
但 `torch.add(x, y)` 和 `(x + y)` 返回一个新的 `Tensor`，原 `x` 和 `y` 不变。

**索引操作**

In [13]:
print(x[:, 1])

tensor([ 0.2553,  0.2170, -0.1960,  1.3610,  1.7581])


**改变形状：`torch.view`**

In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


**仅包含一个元素的 tensor**

可以使用 `.item()` 来得到对应的python数值

In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.2229])
1.2229341268539429


> 更多的运算操作，包括转置，索引，切片，数学运算，线性代数，随机数等，[参阅这里](https://pytorch.org/docs/stable/torch.html)。

## Numpy 桥

* 将一个Torch张量转换为一个NumPy数组是轻而易举的事情，反之亦然。
* Torch张量和NumPy数组将共享它们的底层内存位置，而且几乎不会消耗什么资源, 但是更改一个将更改另一个。
* 对于Tensor不支持的操作，可以先转为Numpy数组处理，之后再转回Tensor。

**将 `Torch` 的 `Tensor` 转换为 `Numpy数组`**

In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


**将 `Numpy` 数组转换为 `Torch` 的 `张量`**

In [19]:
import numpy as np

In [20]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [21]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [22]:
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


> CPU上的所有张量(CharTensor除外)都支持转换为NumPy以及由NumPy转换回来。

**此外在 `PyTorch` 中还有一个和 `np.array` 很类似的接口: `torch.tensor`, 二者的使用十分类似。**

In [23]:
# 新建一个包含 3，4 两个元素的tensor
tensor = torch.tensor([3, 4])
print(tensor)

tensor([3, 4])


In [24]:
scalar = torch.tensor(3)
print(scalar)

tensor(3)


需要注意的是，torch.tensor()总是会进行数据拷贝，新tensor和原来的数据不再共享内存。

所以如果想共享内存的话，建议使用torch.from_numpy()或者tensor.detach()来新建一个tensor, 二者共享内存。

In [25]:
old_tensor = tensor
new_tensor = old_tensor.clone()
new_tensor[0] = 1111
print("Old_{}, New_{}".format(old_tensor, new_tensor))

Old_tensor([3, 4]), New_tensor([1111,    4])


In [26]:
new_tensor = old_tensor.detach()
new_tensor[0] = 1111
print("Old_{}, New_{}".format(old_tensor, new_tensor))

Old_tensor([1111,    4]), New_tensor([1111,    4])


## CUDA上的张量

张量可以使用 `.to` 方法移动到任何设备上

In [27]:
# Run this cell only if CUDA is available
# 将使用`torch.device`来将tensor移入和移出GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # 直接在GPU上创建tensor
    x = x.to(device)                       # 或者使用`.to("cuda")`方法
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # `.to`也能在移动时改变dtype

In [28]:
# 在不支持CUDA的机器下，下一步还是在CPU上运行
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
x = x.to(device)
y = y.to(device)
z = x + y
print(z)

tensor([ 1.6225,  2.2576,  1.2856,  1.8153,  1.0629,  1.7938,  1.2089,  2.2448,
         1.0687,  0.4957, -1.2125,  0.8802,  2.0282, -1.3848,  2.5986,  1.4389])


此外，还可以使用 `tensor.cuda()` 的方式将tensor拷贝到gpu上，但是这种方式不太推荐。

此处可能GPU运算的速度并未提升太多，这是因为x和y太小且运算也较为简单，而且将数据从内存转移到显存还需要花费额外的开销。

GPU的优势需在大规模数据和复杂运算下才能体现出来。